version: '3.8'

services:
  olt-manager:
    build: .
    container_name: easy-huawei-olt-manager
    ports:
      - "3000:3000"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./ftp:/home/ftpuser/ftp
    environment:
      - NODE_ENV=development
    networks:
      - olt-network
    restart: unless-stopped

networks:
  olt-network:
    driver: bridge 