name: easy-huawei

services:
  app:
    build: .
    container_name: easy-huawei-app
    ports:
      - "3000:3000"
      - "5173:5173"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

networks:
  olt-network:
    driver: bridge 