FROM node:20-slim

WORKDIR /app

# Copiar arquivos de configuração
COPY package*.json ./
COPY vite.config.js ./

# Instalar dependências
RUN npm install

# Copiar código fonte
COPY ./src/frontend ./src
COPY ./public ./public

# Expor a porta do Vite
EXPOSE 5173

# Comando para iniciar em modo desenvolvimento
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"] 