version: '3.8'

services:
  olt-manager:
    build: .
    ports:
      - "3000:3000"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - NODE_ENV=production
      - OLT_HOST=${OLT_HOST}
      - OLT_PORT=${OLT_PORT}
      - OLT_USERNAME=${OLT_USERNAME}
      - OLT_PASSWORD=${OLT_PASSWORD}
      - SNMP_COMMUNITY=${SNMP_COMMUNITY}
      - SNMP_VERSION=${SNMP_VERSION}
      - SNMP_PORT=${SNMP_PORT}
    volumes:
      - ./src:/home/ftpuser/ftp/src
      - ./public:/home/ftpuser/ftp/public
      - ./dist:/home/ftpuser/ftp/dist
      - ./logs:/home/ftpuser/ftp/logs
      - ./.env:/home/ftpuser/ftp/.env
      - ./package.json:/home/ftpuser/ftp/package.json
      - ./package-lock.json:/home/ftpuser/ftp/package-lock.json
      - ./docker-compose.yml:/home/ftpuser/ftp/docker-compose.yml
      - ./Dockerfile:/home/ftpuser/ftp/Dockerfile
    restart: unless-stopped 