version: '3.8'

services:
  olt-manager:
    build: .
    ports:
      - "3000:3000"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      - NODE_ENV=production
      - OLT_HOST=${OLT_HOST}
      - OLT_PORT=${OLT_PORT}
      - OLT_USERNAME=${OLT_USERNAME}
      - OLT_PASSWORD=${OLT_PASSWORD}
      - SNMP_COMMUNITY=${SNMP_COMMUNITY}
      - SNMP_VERSION=${SNMP_VERSION}
      - SNMP_PORT=${SNMP_PORT}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./ftp:/home/ftpuser/ftp
    restart: unless-stopped 