version: '3.8'

services:
  olt-manager:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OLT_HOST=${OLT_HOST}
      - OLT_PORT=${OLT_PORT}
      - OLT_USERNAME=${OLT_USERNAME}
      - OLT_PASSWORD=${OLT_PASSWORD}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped 